config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
   resources :posts do
     	collection do
   get 'myposts'
   get 'search'
    end
   end
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/city.rb
class City < ApplicationRecord
	has_many :posts
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :post,inverse_of: :pictures

  has_attached_file :image, styles: {original: "700x450>", thumb: "170x90>"}
  validates_attachment :image, presence: true,
  content_type: { content_type: ["image/jpeg", "image/jpeg", "image/png"] },
  size: { in: 0..1500.kilobytes }

validate :image_count_within_limit, :on => :create
  def image_count_within_limit
    if self.post.pictures(:reload).count >= 5
      errors.add(:base, "Exceeded thing limit is 5")
    end
  end



end

app/models/post.rb
class Post < ApplicationRecord
	is_impressionable counter_cache: true, column_name: :visits, :unique => :all
	searchkick
	belongs_to :user
	belongs_to :category
	belongs_to :city
	has_many :pictures,inverse_of: :post, dependent: :destroy
	validates :title, :description, :price, :city_id, :phone, :category_id, presence: true
	accepts_nested_attributes_for :pictures, allow_destroy: true

	def search_data
		#------------------> rake searchkick:reindex CLASS=Post  <------------------
		  attributes.merge(
		    category_name: category(&:name),
		    city_name: city(&:name)
		    )
        end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :posts, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	  devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :search]
  impressionist :actions=>[:show]
  def index
     @posts = Post.all.order("created_at DESC").paginate(:page => params[:page],  :per_page => 10)
     @most_viued_posts = Post.order(visits: :DESC).limit(5)
  end

def search
    if params[:search].presence || params[:category_id].presence || params[:city_id].presence
      search = params[:search].presence || "*"
      conditions = {}
      conditions[:category_id] = params[:category_id] if params[:category_id].present?
      conditions[:city_id] = params[:city_id] if params[:city_id].present?

      @posts = Post.search search, where: conditions, aggs: [:category,:city], order: {updated_at: :desc}, per_page: 10, page: params[:page]
    else
    redirect_to root_path
    end
end


  def show
   @PostOwner = User.find_by_id(@post.user_id)
   # @pospics = Picture.where(post_id: @post)
   @postpics = @post.pictures
  end

  def myposts
    @myposts = Post.where( :user_id => current_user.id ).order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end


  def new
    @post = current_user.posts.build
    @post.pictures.build

  end

  def create

    @post = current_user.posts.build(post_params)
    @post.category_id = params[:post][:category_id]
    @post.city_id = params[:post][:city_id]

    if @post.save
       if params[:images]
        params[:images].each { |image|
          @post.pictures.create(image: image)
        }
      end
      redirect_to root_path
    else
      redirect_to new_post_path
    end

  end


  def edit
    @post
    if @post.user_id == current_user.id
        render 'edit'
      else
        redirect_to root_path

    end
  end



  def update
    if @post.user_id == current_user.id
    @post.category_id = params[:category_id]
    @post.update(post_params)
      redirect_to @post
      else
        redirect_to root_path
    end
  end

  def destroy
     if @post.user_id == current_user.id
        @post.destroy
        redirect_to myposts_posts_path
    else
     redirect_to root_path
    end
  end

  private

  def post_params
       params.require(:post).permit( :title, :price, :description, :phone, :city_id, :category_id, pictures_attributes: [:image] )
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-responsive-collapse">
         <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a href="/" class="navbar-brand">Avito<span>Clone</span></a>
        </div>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            
            <li><%= link_to "ADD Post", new_post_path %></li>
            <li><%= link_to "My Posts", myposts_posts_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <%end%>
          <% if !user_signed_in? %>
            <li><%= link_to "ADD Post", new_post_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <%end%>
          </ul>


         <%= form_tag search_posts_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
         <div class="form-group">
              <%= text_field_tag :search, params[:search], class: "form-control" %>
        </div>
              <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
          <% end %>


        </div>
      </div>
  </nav>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="author" content="Akki Soufine">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AvitoClone2" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
   <%= javascript_include_tag "application" %>

  </head>
  <body>
      <%= render 'partials/navbar' %>
       <% if current_page?(root_path) || current_page?(search_posts_path) || current_page?(posts_path)%>
       <%# ----- this condition is to show the search bar partial only in index and search pages ----- %>
          <%= render 'partials/searchbar' %>
      <% end %>

    <div class="container">
      <div class="row">
        <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/partials/_CarouselWithContent.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="false">

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
       <% @postpics.each_with_index do |pic, i| %>
           <% if i == 0 %>
          <div class="item active">
            <%= image_tag pic.image.url(:original) %>
          </div>
          <% else %>
          <div class="item">
            <%= image_tag pic.image.url(:original) %>
          </div>
        <% end %>
      <% end %>
  </div>
  


  <!-- Controls -->
  <%unless @postpics.count == 1%>
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <div class="Cindicators">
  
 <ol class="carousel-indicators">
      <% @count = 0 %>
       <% @postpics.each_with_index do |indicator, i|%>
         <% if i == 0 %>
              <%= tag("li", data: {target: '#carousel-example-generic', slide_to: '0'}, class: "active" ) %>
              <%= image_tag @post.pictures.first.image.url(:thumb), class: "img-responsive" %>
              <% else %>
              <%= tag("li", data: {target: '#carousel-example-generic', slide_to: @count += 1}) %>
              <%= image_tag indicator.image.url(:thumb), class: "img-responsive"  %>

         <% end %>

       <% end %>
  </ol>
</div>
<% end %>
</div> 
<%= javascript_include_tag "posts" %>

app/views/partials/_form.html.erb
<%= form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>

<div class="form-group">
  <%= f.label :title %>
   <%= f.text_field :title, :class => 'form-control', :required => true %>
</div>

<div class="form-group">
  <%= f.label :category %>
   <%= collection_select(:post, :category_id, Category.all, :id, :name, {:prompt=>true},{class: "form-control", :required => true}) %>
</div>

<div class="form-group">
  <%= f.label :description, :class => 'control-label' %>
  <%= f.text_area :description, :class => 'form-control', :required => true %>

</div>

<div class="form-group">
   <%= f.label  :price, :class => 'control-label' %> (DH)
   <%= f.number_field  :price, :class => 'form-control', :required => true%>
</div>


<div class="form-group">
  <%= f.label :city %>
   <%= collection_select(:post, :city_id, City.all, :id, :name, {:prompt=>true},{class: "form-control", :required => true}) %>
</div>

<div class="form-group">
  <%= f.label :phone, :class => 'control-label' %>
   <%= f.telephone_field :phone, :class => 'form-control', :required => true %>
</div>

<div class="form-group">
    <%= f.fields_for :pictures do |builder| %>
      <% if builder.object.new_record? %>
        <%= f.label :pictures, "images (only 6 images)", :class => 'control-label' %>
        <%= file_field_tag "images[]", type: :file, multiple: true %>
          <% end %>
    <% end %>
</div>

  <%= f.submit nil, :class => 'btn btn-custom' %>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-responsive-collapse">
         <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a href="/" class="navbar-brand">Avito<span>Clone</span></a>
        </div>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to  new_post_path, style:"margin-top: 2.5px;
    font-size: 16px;
    font-weight: 800;
    background-color: #F44336;
    color: white;
    border-radius: 0;
    height: 45px;" do%>
              <%= fa_icon "edit"%> Add Post<%end%>
            </li>
          <% if user_signed_in? %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <%= fa_icon "user "%> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li><%= link_to "My Posts", myposts_posts_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
           </li>
          <%end%>
          <% if !user_signed_in? %>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <%end%>
          </ul>

        </div>
      </div>
  </nav>
  

app/views/partials/_paginate.html.erb
<div class="text-center">
<%= will_paginate @object, renderer: BootstrapPagination::Rails, previous_label: h("back"), next_label: h("next") %>
</div>

app/views/partials/_searchbar.html.erb
<div class="searchbar">

	<div class="container-fluid sheader">

		<h1>1er site d'annonces gratuites au Maroc</h1>
		<h4>Trouver la bonne affaire parmi <%= @posts.all.count + 5000 %> annonces</h4>

	</div>

	<div class="container-fluid searchbars">

		<%= form_tag search_posts_path, method: :get, class: "navbar-form", role: "search" do %>
			<div class="form-group">
				<%= text_field_tag :search, params[:search], class: "form-control" %>
			</div>
			<div class="form-group">
				<!-- <%= collection_select(@post, :category_id, Category.all, :id, :name, {:prompt=>"Toutes les catégories"},{class: "form-control"}) %> -->
				<%= collection_select(@post, :category_id, Category.all, :id, :name, {:selected => params[:category_id], :prompt=>"Toutes les catégories"},{class: "form-control"}) %>
			</div>
			<div class="form-group">
				<%= collection_select(@post, :city_id, City.all, :id, :name, {:selected => params[:city_id], :prompt=>"Toutes le Maroc"},{class: "form-control"})%>
				<!-- :prompt=>"Toutes le Maroc" -->

			</div>
			<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
		<% end %>

	</div>

</div>

app/views/posts/_form.html.erb
<%= form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>

<div class="form-group">
  <%= f.label :title %>
   <%= f.text_field :title, :class => 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :category %>
   <%= collection_select(:post, :category_id, Category.all, :id, :name, {:prompt=>true},{class: "form-control"}) %>
</div>

<div class="form-group">
  <%= f.label :description, :class => 'control-label' %>
  <%= f.text_area :description, :class => 'form-control' %>

</div>

<div class="form-group">
   <%= f.label  :price, :class => 'control-label' %>
   <%= f.number_field  :price, :class => 'form-control' %>
</div>


<div class="form-group">
  <%= f.label :city %>
   <%= collection_select(:post, :city_id, City.all, :id, :name, {:prompt=>true},{class: "form-control"}) %>
</div>

<div class="form-group">
  <%= f.label :phone, :class => 'control-label' %>
   <%= f.telephone_field :phone, :class => 'form-control' %>
</div>

<div class="form-group">
    <%= f.fields_for :pictures do |builder| %>
      <% if builder.object.new_record? %>
        <%= f.label :pictures, "images (only 6 images)", :class => 'control-label' %>
        <%= file_field_tag "images[]", type: :file, multiple: true %>
          <% end %>
    <% end %>
</div>

  <%= f.submit nil, :class => 'btn btn-custom' %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'partials/form' %>

app/views/posts/index.html.erb
<div class=" col-md-9">
<div class="col-md-12 bord">

<% @posts.each do |post| %>
	<%= link_to post do %>
		<div class="row card-border">
			<div class="col-md-2 timeholder">
			<p class="time"> <%= fa_icon "clock-o "%>  <%= time_ago_in_words(post.created_at) %></p>
			</div>
		            <div class="col-md-3 imgethumbwarp">
		            <div class="bd">
		            <span class="badge"><%= post.pictures.count %></span>
		            </div>
		            <% if post.pictures.present? %>
						<%= image_tag post.pictures.first.image.url(:thumb), class: "imgethumb" %>
						<% else %>
						<%= image_tag "default_image.png", class: "imgethumb"%>
		           <% end %>
		            </div>
		            <div class="col-md-6 post-info">
		                <p class="lead pull-right price"><%= post.price %> DH</p>
		                <p class="mdfont"><%= post.title %></p>
		                <p><%= post.city.name %></p>
		            </div>
		</div>
  <% end %>
<% end %>
</div>
<%= render 'partials/paginate' %>
</div>

<div class="col-md-3 sidebar">
  <div class="well sidebar-nav">
    <% @most_viued_posts.each do |mv| %>
    	<%= link_to mv do %>
    		<div class="row">
    		            <div class="col-md-12 imgesuggestions">
    		            <!-- <div class="bd">
    		            <span class="badge"><%= mv.pictures.count %></span>
    		            </div> -->
    		            <% if mv.pictures.present? %>
    						<%= image_tag mv.pictures.first.image.url(:thumb), class: "imgethumb" %>
    						<% else %>
    						<%= image_tag "default_image.png", class: "imgethumb"%>
    			        <% end %>
    		            </div>
    		            <div class="col-md-12 post-info">
    		                <p class="titlesuggestions text-center"><%= mv.title %></p>
    		                <p class="picesuggestions text-center"><%= mv.price %> DH</p>
    		            </div>
    		</div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/myposts.html.erb
<div class=" col-md-12 bord">
<% if @myposts.present? %>
	<% @myposts.each do |post| %>
		<%= link_to post do %>
			<div class="row card-border">

			            <div class="col-md-3 imgethumbwarp">
			            <div class="bd"><span class="badge"><%= post.pictures.count %></span></div>
			            <% if post.pictures.present? %>
			                    <%= image_tag post.pictures.first.image.url(:thumb), class: "imgethumb" %>
			                <% else %>
							    <%= image_tag "default_image.png", class: "imgethumb"%>
			            <% end %>
			            </div>

			            <div class="col-md-8 post-info">
			                <p class="lead pull-right mypostprice"><%= post.price %> DH</p>
			                <p class="lead"><%= post.title %></p>
			                <p><%= post.city.name %></p>
			            </div>

			            <div class="col-md-2 btn-group actionbtn" role="group" aria-label="...">
								  <%= link_to edit_post_path(post) do%>
								  <button type="button" class="btn btn-primary"><%= fa_icon "pencil"%></button>
								  <%end%>
								  <%= link_to post,  method: :delete, data: { confirm: 'Click Sure! to Delete this item', commit: 'Sure!',cancel: 'cancel'} do %>
								 <button type="button" class="btn btn-danger"><%= fa_icon "trash-o" %></button>
								  <% end %>
								</div>

			</div>
		<% end %>
	<% end %>
<% else %>
	<h2 class="text-center">You Have 0 posts </h2>

	  <div class="text-center">
	  <%=link_to  new_post_path do %>
		 <button type="button" class="btn btn-lg btn-success create" >
		    Create one now !
		  </button>
	  <% end %>
	  </div>

<% end %>
</div>
<div class="text-center">
<%= will_paginate @myposts, renderer: BootstrapPagination::Rails, previous_label: h("back"), next_label: h("next") %>
</div>

app/views/posts/new.html.erb
<h3 class="text-center">create your post</h3>
<%= render 'partials/form' %>

app/views/posts/search.html.erb
<div class=" col-md-9">
	<div class="col-md-12 bord">

<% @posts.each do |post| %>
	<%= link_to post do %>
		<div class="row card-border">
			<div class="col-md-2 timeholder">
			<p class="time"> <%= fa_icon "clock-o "%>  <%= time_ago_in_words(post.created_at) %></p>
			</div>
		            <div class="col-md-3 imgethumbwarp">
		            <div class="bd">
		            <span class="badge"><%= post.pictures.count %></span>
		            </div>
		            <% if post.pictures.present? %>
						<%= image_tag post.pictures.first.image.url(:thumb), class: "imgethumb" %>
						<% else %>
						<%= image_tag "default_image.png", class: "imgethumb"%>
			<% end %>
		            </div>
		            <div class="col-md-6 post-info">
		                <p class="lead pull-right price"><%= post.price %> DH</p>
		                <p class="mdfont"><%= post.title %></p>
		                <p><%= post.city.name %></p>
		            </div>
		</div>
  <% end %>
<% end %>
</div>

<%= render 'partials/paginate' %>
</div>

<div class="col-lg-3 sidebar">
  <div class="well sidebar-nav">
    <% @posts.sort_by(&:visits).reverse!.take(3).each do |post| %>
    	<%= link_to post do %>
    		<div class="row">
    		            <div class="col-md-12 imgesuggestions">
    		            <!-- <div class="bd">
    		            <span class="badge"><%= post.pictures.count %></span>
    		            </div> -->
    		            <% if post.pictures.present? %>
    						<%= image_tag post.pictures.first.image.url(:thumb), class: "imgethumb" %>
    						<% else %>
    						<%= image_tag "default_image.png", class: "imgethumb"%>
    			        <% end %>
    		            </div>
    		            <div class="col-md-12 post-info">
    		                <p class="titlesuggestions text-center"><%= post.title %></p>
    		                <p class="picesuggestions text-center"><%= post.price %> DH</p>
    		            </div>
    		</div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-9">
  <div class="clearfix">
      <h2  class="col-md-6"><%= @post.title %></h2>
  </div>
    <%if @postpics.present? %>
    <%= render 'partials/CarouselWithContent' %>
    <% else %>
    <h4 class="text-center">no images provided from the post owner</h4>
   <% end %>
    <div class="col-md-6">
      <h2><%= @post.price %> DH</h2>
      <p ><%= @post.description %></p>
    </div>

    <div class="col-md-6">
      <h2><%= @PostOwner.name %> </h2>
      <p ><%= @PostOwner.email %></p>
      <p ><%= @post.phone %></p>
    </div>
  </div>
  
  <div class="col-md-3 sidebar">
    <div class="well sidebar-nav text-center">
    <p class="vues">  <%= "Vues: #{@post.impressionist_count} total" %></p>
    </div>
    <div class="well sidebar-nav">
    <h4 class="text-center"> <%= fa_icon "user "%>  <%= @PostOwner.name %> </h4>
    <p class="sidedivider"></p>
    <p> <%= fa_icon "clock-o "%>  <%= time_ago_in_words(@post.created_at) %></p>
    <p> <%= fa_icon "map-marker "%>  <%= @post.city.name %> </p>
    </div>
  </div>